---
- hosts: test
  tasks:
  - name: Copy donkeyid.so to /usr/local/mpsrv/php/lib/php/extensions/no-debug-non-zts-20151012
    copy: src=/Users/rocky/tmp/donkeyid.so dest=/home/rocky/donkeyid.so mode=0755
  - name: 修改配置文件
    blockinfile:
        dest: /home/rocky/test/1.txt
        block: |
          [DonkeyId]
          extension=donkeyid.so
          ;0-4095
          donkeyid.node_id={{num}}
          ;;0-当前时间戳
          donkeyid.epoch=0
        marker: ";{mark} Adding IP address"
  - name: debug info
    debug:
        msg: "{{num}}"
