# 系统内核参数优化
- hosts: all
  tasks:
  - sysctl:
      name: net.ipv4.tcp_max_tw_buckets
      value: 50000
      sysctl_set: yes
      state: present
      reload: yes
  - sysctl:
      name: net.ipv4.tcp_max_syn_backlog 
      value: 8192
      sysctl_set: yes
      state: present
      reload: yes
  - sysctl:
      name: net.core.somaxconn
      value: 8192
      sysctl_set: yes
      state: present
      reload: yes
  - sysctl:
      name: net.ipv4.tcp_tw_reuse
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
  - sysctl:
      name: net.ipv4.tcp_tw_recycle
      value: 0
      sysctl_set: yes
      state: present
      reload: yes
  - sysctl:
      name: net.ipv4.tcp_fin_timeout
      value: 20
      sysctl_set: yes
      state: present
      reload: yes
  - sysctl:
      name: net.ipv4.ip_local_port_range
      value: 1024 65000
      sysctl_set: yes
      state: present
      reload: yes
# modify limit both hard and soft
  - pam_limits:
        domain: root
        limit_type: '-'
        limit_item: nofile
        value: 100000
  - pam_limits:
        domain: root
        limit_type: '-'
        limit_item: nproc
        value: 10000
  - pam_limits:
        domain: '*'
        limit_type: '-'
        limit_item: nofile
        value: 100000
  - pam_limits:
        domain: '*'
        limit_type: '-'
        limit_item: nproc
        value: 10000
